#!/bin/zsh
# sync file changes in $1 directory to $2 host
# super jank, don't put spaces in $2

dir1=$1
dir2=$2
host=$3

rsync -nvrca $dir1/ $host:$dir2/ | \
    head -n-3 | \
    tail -n+2 | \
    grep -v -E "/$" | \
    xargs -i -- bash -c '</dev/tty vimdiff "'$dir1'/{}" "rsync://'$host'/'$dir2'/{}"'

